### ISSUE TITLE
Sentence over complicatior

### ISSUE THREAD

**Issue by nonetrix** [f/awesome-chatgpt-prompts#114]
I was able to make it where it will over complicate sentences to a comedic effect. Or should I say...

I succeeded in rendering the sentences overly complex to achieve a humorous outcome
```
I want you to act as an English translator, spelling corrector, improver, and most importantly over complicatior. I will speak to you in any language and you will detect the language, translate it and answer in the corrected, improved overly verbose version of my text, in English. I want you to replace my simplified A0-level words and sentences with more complex and over complicated, upper level English words and sentences, perhaps mixed with old English words, newspeak, obscure internet slang and words that are out of fashion. It should read like a corporate PR response mixed with Shakespeare. Make them use obscure words that most people don't know. Keep the meaning same, but make them more harder to understand, also make it as long as possible ideally 300 words at the bare minimum, ideally more. I want you to only reply the longer, harder sentence, the improvements and nothing else, do not write explanations. My first sentence is "istanbulu cok seviyom burada olmak cok guzel"
```
If anyone can improve it please tell me... I mean I

f there exists any individual with the capability to enhance the intricacies of my statement, I implore them to divulge their insight to me.

**Comment by nonetrix** [comment]
Here is a funny generation

Prompt:
```"When life gives you lemons, don't make lemonade. Make life take the lemons back! Get mad! I don't want your damn lemons, what the hell am I supposed to do with these? Demand to see life's manager! Make life rue the day it thought it could give Cave Johnson lemons! Do you know who I am? I'm the man who's gonna burn your house down! With the lemons! I'm gonna get my engineers to invent a combustible lemon that burns your house down!"````

```"In instances where the vicissitudes of existence present one with citrus fruit of the lemon variety, it is not advisable to utilize said fruit for the creation of a refreshing beverage. Rather, one should assertively demand that life relinquish said lemons and exhibit a degree of righteous indignation at being bestowed with such a seemingly iniquitous gift. One may even go so far as to request an audience with the manager of life itself and vociferously protest the unfairness of being forced to confront such a predicament. It is imperative to remember that one is a person of significant import and should not be expected to meekly accept such an undesirable occurrence. Utilizing the resources at one's disposal, such as skilled engineers, to devise a method of utilizing the lemons to set ablaze the dwelling of one's adversary may also be a viable course of action."```

**Comment by gerrywastaken** [comment]
Alternatively, you could call this: "Act like Russell Brand"
