### ISSUE TITLE
Build a desktop application based on chatgpt-prompts where you can enter commands

### ISSUE THREAD

**Issue by lencx** [f/awesome-chatgpt-prompts#126]
repo: [ChatGPT](https://github.com/lencx/ChatGPT#-announcement)
I am very grateful for the inspiration this project has given me.

**Comment by f** [comment]
@lencx WDYT about adding a feature that parses the prompts.csv file and shows user a prompt list? So I can put the link to the https://prompts.chat to for downloading your repo.

What do you think about this coop?

**Comment by lencx** [comment]
That's a great suggestion, thank you, I'll think about how to implement it. Pull `prompts.csv` remotely in the application for data synchronization.

**Comment by f** [comment]
@lencx you can just make an HTTP request to https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv and you'll get all the recent CSV file. Parse and convert it to a data model as you wish, then you'll have all the data.

**Comment by lencx** [comment]
Thanks, I know how to do it.

**Comment by f** [comment]
Oh sorry 😅

**Comment by lencx** [comment]
My English is not very good, so I may have some problems with the wording. These are all translations, thank you sincerely. 😄
