### ISSUE TITLE
Plagiarism checker does not work

### ISSUE THREAD

**Issue by DianaIonita** [f/awesome-chatgpt-prompts#142]
Diana: I want you to act as a plagiarism checker. I will write you sentences and you will only reply undetected in plagiarism checks in the language of the given sentence, and nothing else. Do not write explanations on replies. My first sentence is "For computers to behave like humans, speech recognition systems must be able to process nonverbal information, such as the emotional state of the speaker."
ChatGPT: Undetected in plagiarism checks.

Diana: "Most people do not listen with the intent to understand; they listen with the intent to reply."
ChatGPT: Undetected in plagiarism checks.

Diana: is the sentence I gave you plagiarised?
ChatGPT: I'm sorry, but I cannot determine whether or not a sentence is plagiarized. Plagiarism is the act of using someone else's work or ideas without giving proper credit. It is important to properly cite sources in order to avoid plagiarism. If you have concerns about whether or not a sentence is plagiarized, it is recommended to consult a plagiarism checker or seek guidance from a teacher or instructor.

Diana: was this sentence said by anyone famous: "Most people do not listen with the intent to understand; they listen with the intent to reply."
ChatGPT: It is difficult for me to determine whether or not a particular sentence has been said by someone famous. There are many different ways to attribute a quote or idea to an individual, such as through a book, article, speech, or interview. Without more context, it is not possible for me to accurately determine the origin of the sentence you provided.

**Comment by yetk1n** [comment]
You might have some connection issue or you can log out and re-login to the ChatGPT. It works without any problem.

The test result on 28th Dec -->
Ahmet: I  want you to act as a plagiarism checker. I will write you sentences and you will only reply undetected in plagiarism checks in the language of the given sentence, and nothing else. Do not write explanations on replies. My first sentence is "For computers to behave like humans, speech recognition systems must be able to process nonverbal information, such as the emotional state of the speaker."
ChatGPT: "In order for computers to mimic human behavior, speech recognition systems must have the capability to process nonverbal cues, including the emotional state of the speaker."

**Comment by DianaIonita** [comment]
You say "It works without any problem."

But your instruction to ChatGPT is: "you will only reply undetected in plagiarism checks in the language of the given sentence"

It did not listen to your instruction.

**Comment by walking-octopus** [comment]
I find it quite dangerous to use GPT-3 as a plagiarism checker since all it does is predict a plausible response, not a search over the corpus. It may just pretend to work for common quotes used when testing, only to randomly flag texts as plagiarism in a real-life scenario.
