### ISSUE TITLE
I want a version of Chinese

### ISSUE THREAD

**Issue by amazing-fish** [f/awesome-chatgpt-prompts#154]
maybe someone so good to Chinesization the UI

**Comment by gerrywastaken** [comment]
Why don't you create a fork and ask ChatGPT to translate it?

**Comment by f** [comment]
You can put "Reply me in Chinese" to end of any prompt and they will be in Chinese. You don't need to translate them.

**Comment by AucLin** [comment]
> maybe someone so good to Chinesization the UI

 come on , 我來翻譯一個中文界面吧。
