### ISSUE TITLE
smart domain names?

### ISSUE THREAD

**Issue by deadcoder0904** [f/awesome-chatgpt-prompts#20]
thanks for this repo! the **english translator and improver** is a good prompt for rephrasing text to make it more sophisticated. makes me sound smarter 😂 

bdw, i just saw https://smartynames.com yesterday & the results were terrific. would love a similar prompt if anyone can come up with it!

**ps**: you've mistyped `prompt` as `promt`... just <kbd>ctrl + f</kbd> `promt` on https://github.com/f/awesome-chatgpt-prompts

**Comment by f** [comment]
Done.

**Comment by deadcoder0904** [comment]
oh & the `promt` is still a typo which only you can fix :)
