### ISSUE TITLE
I want to add my free guide on - Mastering ChatGPT Prompts!

### ISSUE THREAD

**Issue by twf-nikhila** [f/awesome-chatgpt-prompts#217]
Hey @f ,

I want to add this free course:

**Mastering ChatGPT Prompts!**

Link: https://heynikhila.gumroad.com/l/Mastering-chatGPT-Prompts

Please add it or provide details on how to contribute to this repository.

Thank you!

**Comment by Manamama** [comment]
It is not free:
`🔓 UNLOCK Full Potential `
It is thus a lie.
