### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by mda1125** [f/awesome-chatgpt-prompts#231]
I've followed the outline in the Readme and the Prompts.csv but when I attempt a git push origin <my branch name> I'm getting a 403

If I'm not part of this repo, and I want to suggest a prompt, do I just need to open an issue?

**Comment by mda1125** [comment]
I had to create a Fork into my own repo and make the changes.  Then from my repo I created a Pull Request.  Thanks to ChatGPT for walking me thru all this as I'm a newbie.

**Comment by Vazno** [comment]
issue can be closed
https://github.com/f/awesome-chatgpt-prompts/pull/232
