### ISSUE TITLE
I got the following trying to open on a MacBook Pro w/ 12.6.2

### ISSUE THREAD

**Issue by sangfroid** [f/awesome-chatgpt-prompts#262]
“ChatGPT” cannot be opened because the developer cannot be verified.

**Comment by Vazno** [comment]
Are you trying to download https://github.com/lencx/ChatGPT ?
Turn this on:
<img width="715" alt="212658326-97f6c753-d070-4cb8-973c-e3be359932aa" src="https://user-images.githubusercontent.com/96925396/213520926-86a80ff8-cb3d-4e81-b6b2-7ef5ad4537d7.png">
Here is a link to the related issue:
https://github.com/lencx/ChatGPT/issues/219

**Comment by Vazno** [comment]
https://support.apple.com/en-sg/guide/mac-help/mh40616/mac
