### ISSUE TITLE
About Section on Github has typo

### ISSUE THREAD

**Issue by AmyMagdalena** [f/awesome-chatgpt-prompts#35]
Currently says: This repo includes ChatGPT promt curation to use ChatGPT better.

The simple fix:  This repo includes ChatGPT prompt curation to use ChatGPT better.

Or I wrote this snappier text: This repo contains awesome curated ChatGPT prompts.

**Comment by ademidun** [comment]
Great idea amy. I think you can even remove "this repo contains" to make it even snappier.

> Examples of awesome ChatGPT prompts that get awesome responses.
