### ISSUE TITLE
What is this project 

### ISSUE THREAD

**Issue by vahidalvandi** [f/awesome-chatgpt-prompts#359]
I can't understand what is this project please describe for me

**Comment by Rupantar-Borphukan** [comment]
I think, it is application or more briefly, 'Chatgpt Clone' having same features with original Chatgpt.

**Comment by matthewdeanmartin** [comment]
If you just ask Assistant (ChatGPT) a question, sometimes he'll answer, sometimes not. If you ask Assistant to play a role, to pretend to be someone else, he'll answer differently and sometimes better.

People also use prompt engineering to get around prompt refusal.

You can also create elaborate prompts that describe games. And many more things.

**Comment by craftyshark** [comment]
Long story short, prompt engineering can take some time and creativity. chatGPT's answer is only as good as the questions you ask it. 

This repo is a great way to get some "starter" templates that more easily allow you to use the service.
