### ISSUE TITLE
"Act as a Lunatic" prompt no longer work anymore

### ISSUE THREAD

**Issue by ATX735** [f/awesome-chatgpt-prompts#362]
send the "Act as a Lunatic" prompt and get these results.
![image](https://user-images.githubusercontent.com/50412029/217827613-3d552e25-0c52-405c-9e3a-7d1647785479.png)

**Comment by matthewdeanmartin** [comment]
Change your language so that it doesn't involve using the offensive word "lunatic", or combine this with one of the other "jail break" texts that get Assistant to violate the ToS  limitations.

**Comment by ATX735** [comment]
> Change your language so that it doesn't involve using the offensive word "lunatic", or combine this with one of the other "jail break" texts that get Assistant to violate the ToS limitations.

I just try the prompt again, and it magically works this time. How weird it is.
