### ISSUE TITLE
Can I use my API to connect with chatgpt3?

### ISSUE THREAD

**Issue by Johnny-Zhang92** [f/awesome-chatgpt-prompts#365]

**Comment by matthewdeanmartin** [comment]
Yes, it costs money (but not a lot) and you get davinci instead of Assistant/ChatGPT - https://openai.com/api/ OpenAI said they will be offering Assistant/ChatGPT soon.

**Comment by Johnny-Zhang92** [comment]
> 
Thank you for your reply. It helped me a lot.

**Comment by Johnny-Zhang92** [comment]
> Yes, it costs money (but not a lot) and you get davinci instead of Assistant/ChatGPT - https://openai.com/api/ OpenAI said they will be offering Assistant/ChatGPT soon.

Thank you for your reply. It helped me a lot.

**Comment by mirnyyy** [comment]
an where I can enter my API key?
can anybody tell me?

**Comment by matthewdeanmartin** [comment]
You look like you might know python, this is my set of scripts I use https://github.com/matthewdeanmartin/cheaper_openai 

I am using a .env file to hold the API key, you set it like this: https://github.com/matthewdeanmartin/cheaper_openai/blob/main/chats/client_utils.py
