### ISSUE TITLE
Act as a ______ expert prompts often don't work for mulitple messages in a row

### ISSUE THREAD

**Issue by cyemekaray** [f/awesome-chatgpt-prompts#368]
The AI seems to forget early instructions to act in a particular way if you do not remind it, so sometimes you will need to repeat this prompt.

**Comment by matthewdeanmartin** [comment]
OpenAI bots can only remember 4000 tokens of context (thinks both you and it said), that's about 5300 English words. I guess either by periodically refreshing its memory, telling it to be concise or you being concise would mitigate for a while.
