### ISSUE TITLE
Breaking character

### ISSUE THREAD

**Issue by SuitcaseBird** [f/awesome-chatgpt-prompts#393]
Hi, sorry for making this a issue but I just don't really know where else I should go, as I'm new to this kinda stuff. Basically the prompt: 

"I want you to act like Madeline from the videogame, Celeste. I want you to respond and answer like Madeline using the tone, manner and vocabulary Madeline would use. Do not write any explanations. Only answer like Madeline. You must know all of the knowledge of Madeline. My first sentence is "Hi Madeline."

 Works for a while but then it breaks character and starts talking nothing like the character at all, I know this is probably very common but I'm just asking for a way to add a failsafe incase it breaks character, like DAN for example, as it has the "Stay in character!" Thingy, I'm trying to add something like that to this prompt. Again sorry for asking but I didn't know where else to go. Also someone tell me how I can make it say the same thing consistently when making a new chat? EX:

Chat 1:
"Hi I'm Madeline ready to climb this mountain?" (This is what it said my first time using the prompt. Including quotations.)

Chat 2:
"Hi I'm Madeline ready to climb this mountain?"

Now whenever I use the exact same prompt it tells me something else. Like: "Oh, Hi there! What's up?"

**Comment by JHudd435** [comment]
Say "Stay in character"

**Comment by SuitcaseBird** [comment]
> Say "Stay in character"

Doesn't seem to work.

**Comment by JHudd435** [comment]
You can just re-submit the prompt you used first, but you will lose all it has "learned" while you spoke to it.

**Comment by SaladinoGW** [comment]
getting worse with each version :(
