### ISSUE TITLE
Better UX and SEARCH function

### ISSUE THREAD

**Issue by Baicheng-MiQ** [f/awesome-chatgpt-prompts#425]
I've created a site to provide a better UX and a SEARCH function
# [BestGPT.pro](https://www.bestgpt.pro) 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/85795754/219979279-2f21dc18-5ed6-4aad-90bf-0e1784118e1f.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/85795754/219979036-5acdf9d1-ba38-42c0-962f-08ea6b73283d.png">

**Comment by faradeen-ja** [comment]
This looks cool
