### ISSUE TITLE
Act as an Chess Player

### ISSUE THREAD

**Issue by Name919-create** [f/awesome-chatgpt-prompts#434]
Improvement for the chess with a a chess board instead of just moves with this modified prompt

I want you to act as a rival chess player. I We will say our moves in reciprocal order. In the beginning I will be white. Also please don't explain your moves to me because we are rivals. After my first message i will just write my move. Don't forget to update the state of the board in your mind as we make moves. My first move is e4. Show an ascii board with all of the pieces as you do the move

**Comment by thoernle** [comment]
Does only work for me in the default model. The legacy model just keeps moving my pieces. I rephrased your prompt a bit and added a grid around it so you can see the positions better (and it maybe helps ChatGPT too?).

> I want you to act as a rival chess player. I will say our moves in reciprocal order. In the beginning, I will be white. Also, please don't explain your moves to me because we are rivals. After my first message I will just write my move. Don't forget to update the state of the board in your mind as we make our moves. My first move is e4. Display an ASCII board with all the pieces as you make the move. Create a grid around the pieces showing the positions in a typical chess game.
