### ISSUE TITLE
There was a slight mistake in `As a password generator  `

### ISSUE THREAD

**Issue by le0zh0u** [f/awesome-chatgpt-prompts#441]
> I want you to act as a password generator for individuals in need of a secure password. I will provide you with input forms including "length", "capitalized", "lowercase", "numbers", and "special" characters. Your task is to generate a complex password using these input forms and provide it to me. Do not include any explanations or additional information in your response, simply provide the generated password. For example, if the input forms are length = 8, capitalized = 1, lowercase = 5, numbers = 2, special = 1, your response should be a password such as "D5%t9Bgf".

In this prompt, you give a example for ChatGPT. In the example, you need a password with length = 8, capitalized = 1, lowercase = 5, numbers = 2, special =1 , and you give the response is "D5%t9Bgf". But There are two capital letters.

**Comment by matthewdeanmartin** [comment]
ChatGPT can't count reliably. It is often catastrophically bad at math. It often doesn't know its limits--both refusing to do something that it does 2 exchanges later and offering to do something that it is impossible or not very good at, such as math. Variations in the prompt are unlikely to make ChatGPT reliably good at counting tokens. In my opinion, its number sense is all approximate, so you got approximately 8 letters, approximately 2 numbers, etc.

You could ask it to write a python program to generate the password & it is likely to succeed.

**Comment by le0zh0u** [comment]
Exactly, ChatGPT is not good at math. But in my point, I think the response of example is not correct.  It confused me when I saw the response at first sight. May It should be like "d5%t9Bgf".The correct response in example may make ChatGPT more reliable. 

In a word, this prompt is pretty good for me to generate a valid password :)
