### ISSUE TITLE
Doesn't Work in ChatGPT Plus

### ISSUE THREAD

**Issue by websmyths** [f/awesome-chatgpt-prompts#445]
It doesn't show prompts and the extension shows the following errors in ChatGPT Plus:

Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
Context
https://chat.openai.com/chat
Stack Trace
contentScript.js:1 (anonymous function)
1

**Comment by Xi-Gong** [comment]
I encounter this problem either, Chat GPT Plus seems work in different manner.

**Comment by mikyzqz** [comment]
Il Dom 26 Feb 2023, 13:09 Roy ***@***.***> ha scritto:
