### ISSUE TITLE
Please limit the sort of people that can open issues

### ISSUE THREAD

**Issue by matthewdeanmartin** [f/awesome-chatgpt-prompts#485]
@f - if you go to settings/interaction_limits you can say "no issues can be opened by people who just opened an account" The restriction expires after 1/2 year (at most) but you'll get 1/2 year of peace.

I watch the repo (and that is probably why spammers target you, you got a lot of watchers) and it is being flooded with spam many who opened their account less than 24 hours ago. (good chance you will ignore this as just more of the tsunami of spam!)

Anyhow, thanks for maintaining the repo.

**Comment by f** [comment]
Thank you for the tip! Just enabled it.
