### ISSUE TITLE
PR to awesome list tracker

### ISSUE THREAD

**Issue by abbaselmas** [f/awesome-chatgpt-prompts#49]
awesome list tracker has chatgpt session.
A PR to [that session](https://github.com/trackawesomelist/trackawesomelist/blob/main/content/Kamigami55/awesome-chatgpt/README.md) will be more convenient.

thanks for your hard work on aggregating all these info.

**Comment by meroo36** [comment]
Helpful resource. Thanks for sharing.

**Comment by Broteymkr** [comment]
> awesome list tracker has chatgpt session.
> A PR to [that session](https://github.com/trackawesomelist/trackawesomelist/blob/main/content/Kamigami55/awesome-chatgpt/README.md) will be more convenient.
> 
> thanks for your hard work on aggregating all these info.
