### ISSUE TITLE
How about the idea of categorizing prompts?

### ISSUE THREAD

**Issue by omerimzali** [f/awesome-chatgpt-prompts#76]
Over 108 prompts have been committed, and now the repo has a .csv file. it might be good to create categories for prompts. It'll be easy to find any specific prompt. The first categories that come to my mind are programming, personalities or persons or experts (I'm not sure how to categorize the persons), tools, etc. 

@f

**Comment by f** [comment]
Maybe ChatGPT itself can separate these into categories :)

**Comment by nicolasdb** [comment]
#320 
this could maybe linked with my proposition.
