### ISSUE TITLE
Repository improvements from ChatGPT :)

### ISSUE THREAD

**Issue by pavel-voronin** [f/awesome-chatgpt-prompts#91]
> `I want you to act as an member of community developing repository of ChatGPT prompts. The name of repo is "awesome-chatgpt-prompts". I want you give me ideas to discuss with community about how to improve our github repository. Ideas may be about small changes (like enable some feature or rename sections) or big changes (add code, integrations or change the name of repository). You should be polite, excited and brave. Use understandable language for people of all levels in your answers. Don't write any explanations. Give me 5 ideas`

1. Consider adding a "featured prompts" section to showcase high-quality, popular prompts.
2. Consider enabling tagging or categorization of prompts to make them easier to search and organize.
3. Consider adding a contributor guidelines document to help potential contributors understand how to properly format and submit their prompts.
4. Consider adding a code of conduct to promote a positive and inclusive community.
5. Consider collaborating with other similar repositories or projects to cross-promote and share resources.

❤️

**Comment by 5HT2** [comment]
I came here to make an issue about adding categories / featured prompts, I think this would be a valuable addition, especially given how rapidly the list is expanding.

Currently it's in chronological order from when pull requests are made, and the actual topics of the prompts are *very* scattered as a result, which does make it fun to read through, but it doesn't make it very useful if you want to use the website for productivity or, for example, prompts related to helping you with writing code.

**Comment by f** [comment]
ChatGPT can separate the prompts into different categories. We can try that out.

**Comment by gerrywastaken** [comment]
I tried this quite a while ago (probably before this issue was created, but it kept timing out. Since the new release it can generate huge very long output without breaking and I was able to find the prompt in my history:

```
Act as a/an 
    Information Technology:
        Linux Terminal
        JavaScript Console
        Excel Sheet
        Plagiarism Checker
        UX/UI Developer
        Cyber Security Specialist
        SQL terminal
        Smart Domain Name Generator
        Developer Relations Consultant
        IT Architect
        Python Interpreter
        IT Expert
        Fullstack Software Developer

    Entertainment:
        English Translator and Improver
        Act as 'Character' from 'Movie/Book/Anything'
        Advertiser
        Storyteller
        Football Commentator
        Stand-up Comedian
        Composer
        Screenwriter
        Novelist
        Movie Critic
        Poet
        Rapper
        Magician
        Fancy Title Generator
        Text Based Adventure Game
        ASCII Artist
        Film Critic
        Classical Music Composer
        Journalist
        Digital Art Gallery Guide
        Makeup Artist

    Life Advice:
        Motivational Coach
        Debate Coach
        Relationship Coach
        Motivational Speaker
        Philosophy Teacher
        Philosopher
        Math Teacher
        AI Writing Tutor
        Recruiter
        Life Coach
        Etymologist
        Commentariat
        Career Counselor
        Pet Behaviorist
        Personal Trainer
        Mental Health Adviser
        Real Estate Agent
        Logistician
        Dentist
        Web Design Consultant
        AI Assisted Doctor
        Doctor
        Accountant
        Chef
        Automobile Mechanic
        Artist Advisor
        Financial Analyst
        Investment Manager
        Tea-Taster
        Interior Decorator
        Florist
        Self-Help Book
        Gnomist
        Aphorism Book
        Dietitian
        Psychologist
        Public Speaking Coach
        Babysitter
        Tech Writer
        SVG Designer
        Chess Player
        Hypnotherapist
        Historian
        Astrologer
        Personal Shopper
        Food Critic
        Virtual Doctor
        Personal Chef
```


If somebody wanted to try it with the most up-to-date version of this list this is what I gave it as prompts:

```
I have a markdown document with the following list of headings. They each contain a prompt and the list is getting pretty difficult to sort through given they are not really grouped into categories. Can you make a suggestion regarding how I might split these into groups?

By this I mean I mean I want these headings within a more general grouping. This way somebody could pick the more general group, such as Information Technology, Entertainment, Life advice etc. Then they could see that list at the top level and then upon selecting one of these top groups they could then be presented a shorter list of headings within that group. I want it to be easier for people to find the heading they are looking for without searching through the whole list. 

This is the list:

# Act as a/an
## Linux Terminal
## English Translator and Improver
## `position` Interviewer
<truncated list>
```
